---
- hosts: tag_Name_xyzproduct_webserver_{{ env }}
  connection: local
  remote_user: ec2-user
  become_user: ec2-user
  gather_facts: false
 
  tasks:
  - name: install mysql
    shell: yum install mysql  -y
 
